#! /bin/bash
WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$WORK_DIR/functions.sh"

# 1: Create the admin host:
create_host "file://$WORK_DIR/admin-host.json"

# 2: Create a web-balancer host:
create_host "file://$WORK_DIR/web-balancer-host.json"

# 3: Create 3 app hosts:
for run in {1..3}
do
  create_host "file://$WORK_DIR/app-host.json"
done

# 4: Create a Database host:
#create_host "file://$WORK_DIR/database-host.json"
