#! /bin/bash
WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$WORK_DIR/functions.sh"

function pretty_create_host() {
  echo "================================================================================"
  echo "$1:";
  create_host "file://$WORK_DIR/$1.json" $2;
}

# 1: Create the admin host:
pretty_create_host "admin-host"

# 2: Create a web host:
pretty_create_host "web-host"

# 3: Create 3 app hosts:
pretty_create_host "app-host" 3

# 4: Create a Data host:
pretty_create_host "data-host"

echo "================================================================================"
